#!/usr/bin/env python3
"""Generates preview/index.html: static mock of the home page using the real built CSS/JS (no Salla widgets)."""
import pathlib
U=lambda i,w=900:f"https://images.unsplash.com/photo-{i}?auto=format&fit=crop&w={w}&q=80"
im=["1441986300917-64674bd600d8","1445205170230-053b83016050","1483985988355-763728e1935b","1469334031218-e382a71b716b","1490481651871-ab68de25d43d","1441984904996-e0b6ba687e04"]
card=lambda i,n,p:f'<div class="luxe-reveal luxe-card-wrap"><div class="s-product-card-entry"><div class="s-product-card-image"><a href="#"><img src="{U(im[i%6],700)}" alt="" loading="lazy" style="width:100%;height:100%;object-fit:cover"></a><button class="luxe-qv-btn" type="button">معاينة سريعة</button></div><div class="s-product-card-content" style="padding-top:.75rem"><h3 class="s-product-card-content-title" style="font-size:1rem"><a href="#">{n}</a></h3><div style="font-weight:800;margin-top:.2rem">{p} ر.س</div></div></div></div>'
cats="".join(f'<a href="#" class="luxe-cat-card luxe-reveal" data-reveal-delay="{k*.08}" data-cursor="تسوّق"><span class="luxe-cat-card__num">0{k+1}</span><span class="luxe-cat-card__media"><img src="{U(im[k+1],700)}" alt=""></span><span class="luxe-cat-card__label"><span>{t}</span><i>←</i></span></a>' for k,t in enumerate(["الجديد","الأساسيات","المناسبات"]))
prods="".join(card(i,n,p) for i,(n,p) in enumerate([("معطف صوف كلاسيكي","890"),("فستان حرير","640"),("حقيبة جلد","1,250"),("وشاح كشمير","320")]))
slides="".join(f'<a class="luxe-slide luxe-collection" href="#" draggable="false" data-cursor="اسحب"><span class="luxe-collection__arch"><img src="{U(im[k],600)}" alt="" draggable="false"></span><span class="luxe-collection__cap"><strong>{t}</strong><small>{c}</small></span></a>' for k,(t,c) in enumerate([("الربيع","٢٤ قطعة"),("الأساسيات","١٢ قطعة"),("المناسبات","١٨ قطعة"),("الإكسسوارات","٣٠ قطعة"),("الصيف","٢٠ قطعة")]))
quotes="".join(f'<figure class="luxe-slide luxe-quote"><span class="luxe-quote__mark">“</span><blockquote>{t}</blockquote><div class="luxe-quote__stars">★★★★★</div><figcaption><strong>{n}</strong><span>عميل</span></figcaption></figure>' for n,t in [("سارة","جودة استثنائية وتغليف فاخر. تجربة شراء لا تُنسى."),("محمد","توصيل سريع وخدمة راقية. سأكرر الطلب بالتأكيد."),("نورة","تصاميم أنيقة وأسعار مناسبة."),("خالد","أفضل متجر تعاملت معه.")])
social="".join(f'<a class="luxe-social-grid__item luxe-reveal" data-reveal-delay="{k*.06}" href="#"><img src="{U(im[k],500)}" alt=""></a>' for k in range(6))
mq="".join('<div class="luxe-marquee__group">'+"".join(f"<span>{w}</span><b>✦</b>" for w in ["شحن سريع","جودة فاخرة","إرجاع مجاني","تصاميم حصرية"])+'</div>' for _ in range(4))
html=f'''<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Luxe — static design preview</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Kufi+Arabic:wght@400;600;800&family=Tajawal:wght@400;500;700&family=Syne:wght@500;700;800&display=swap">
<link rel="stylesheet" href="../public/app.css">
<style>:root{{--luxe-bg:#f2ece1;--luxe-surface:#fbf8f2;--luxe-text:#16120e;--luxe-muted:#6f665b;--luxe-accent:#c4532d;--luxe-ink:#1e3a2f;--color-primary:#16120e}}.lx-note{{position:fixed;bottom:8px;left:8px;background:#000c;color:#fff;font:11px sans-serif;padding:4px 8px;z-index:99999}}</style>
<script>window.luxe={{animations:true,intensity:"medium",parallax:true,pageTransition:true,cartDrawer:false,quickView:false,cursor:true}}</script></head>
<body class="theme-luxe luxe-motion lx-ready"><div class="app-inner flex flex-col min-h-full">
<header class="store-header luxe-header"><div class="luxe-announce"><span>شحن مجاني للطلبات فوق 300 ر.س</span></div>
<div id="mainnav" class="main-nav-container luxe-nav flex items-center"><div class="inner w-full"><div class="container"><div class="flex items-center justify-between" style="height:76px"><div class="flex items-center" style="gap:2.5rem"><strong style="font-family:var(--lx-display);font-size:1.8rem;font-weight:800">LUXE</strong><nav class="hidden lg:flex" style="gap:1.75rem;font-size:.95rem;font-weight:700"><a>الرئيسية</a><a>النساء</a><a>الرجال</a><a>الإكسسوارات</a><a>العروض</a></nav></div><div class="flex items-center"><button class="luxe-icon-btn">⌕</button><button class="luxe-icon-btn">♡</button><button class="luxe-icon-btn">👜</button></div></div></div></div></div></header>
<main>
<section class="luxe-hero"><span class="luxe-hero__blob"></span><div class="container luxe-hero__grid"><div class="luxe-hero__copy"><p class="luxe-eyebrow luxe-eyebrow--line" data-hero="fade">المجموعة الجديدة ٢٠٢٦</p><h2 class="luxe-hero__title" data-split>أناقة تُصنع بإتقان</h2><p class="luxe-hero__text" data-hero="fade">قطع مختارة بعناية تجمع بين الفخامة والبساطة.</p><div class="luxe-hero__cta" data-hero="fade"><a href="#" class="luxe-btn luxe-btn--solid luxe-btn--lg luxe-magnetic"><span class="luxe-btn__label">تسوّق الآن</span></a><a href="#" class="luxe-btn luxe-btn--outline luxe-btn--lg"><span class="luxe-btn__label">اكتشف القصة</span></a></div></div>
<div class="luxe-hero__visual" data-hero="visual"><div class="luxe-hero__arch"><img data-parallax-img src="{U(im[0],1200)}" alt=""></div><div class="luxe-hero__badge"><svg viewBox="0 0 120 120"><defs><path id="c" d="M60,60 m-46,0 a46,46 0 1,1 92,0 a46,46 0 1,1 -92,0"/></defs><text><textPath href="#c" textLength="285">توصيل مجاني • جودة مضمونة • توصيل مجاني • جودة مضمونة • </textPath></text></svg><i>←</i></div><span class="luxe-hero__chip">✦ وصل حديثاً</span></div></div></section>
<section class="luxe-marquee is-ink"><div class="luxe-marquee__track">{mq}</div></section>
<section class="luxe-section container"><header class="luxe-section__head luxe-reveal"><h2 class="luxe-section__title">تسوّق حسب التصنيف</h2><span class="luxe-section__count">(3)</span></header><div class="luxe-cat-grid">{cats}</div></section>
<section class="luxe-section container"><header class="luxe-section__head luxe-reveal"><div><p class="luxe-eyebrow">الأكثر طلباً</p><h2 class="luxe-section__title">منتجات مختارة</h2></div><a class="luxe-btn luxe-btn--link luxe-btn--md"><span class="luxe-btn__label">عرض الكل</span></a></header><div class="luxe-product-grid">{prods}</div></section>
<section class="luxe-story"><div class="container luxe-story__grid"><div class="luxe-story__frame luxe-reveal"><div class="luxe-story__media"><img data-parallax-img src="{U(im[4],1200)}" alt=""></div></div><div class="luxe-story__copy"><p class="luxe-eyebrow luxe-eyebrow--line luxe-reveal">قصتنا</p><h2 class="luxe-story__title" data-split>حرفة تتوارثها الأجيال</h2><p class="luxe-story__text luxe-reveal">نؤمن بأن الجمال في التفاصيل. كل قطعة نقدمها تحمل قصة من الإتقان والاهتمام.</p><ul class="luxe-stats luxe-reveal"><li><strong data-count="12">12</strong><span>سنة خبرة</span></li><li><strong data-count="48">48</strong><span>ألف عميل</span></li><li><strong data-count="300">300</strong><span>قطعة حصرية</span></li></ul><div class="luxe-reveal"><a class="luxe-btn luxe-btn--light luxe-btn--lg"><span class="luxe-btn__label">اقرأ المزيد</span></a></div></div></div></section>
<section class="luxe-section luxe-section--bleed"><div class="container"><header class="luxe-section__head luxe-reveal"><h2 class="luxe-section__title">المجموعات</h2><span class="luxe-section__hint">اسحب ⇄</span></header></div><div class="luxe-slider" data-luxe-slider><div class="luxe-slider__track">{slides}</div><div class="luxe-slider__nav"><button class="luxe-icon-btn luxe-icon-btn--ring" data-slider-prev>→</button><button class="luxe-icon-btn luxe-icon-btn--ring" data-slider-next>←</button></div></div></section>
<section class="luxe-section container"><header class="luxe-section__head luxe-reveal"><h2 class="luxe-section__title">ماذا يقول عملاؤنا</h2></header><div class="luxe-slider" data-luxe-slider><div class="luxe-slider__track">{quotes}</div></div></section>
<section class="luxe-section container"><header class="luxe-section__head luxe-reveal"><div><h2 class="luxe-section__title">تابعنا على إنستغرام</h2><p class="luxe-eyebrow">@yourstore</p></div></header><div class="luxe-social-grid">{social}</div></section>
<section class="luxe-section container"><div class="luxe-newsletter luxe-reveal"><span class="luxe-newsletter__sticker">✦</span><div class="luxe-newsletter__body"><h2 class="luxe-newsletter__title">انضم إلى قائمتنا</h2><p>اشترك ليصلك كل جديد وعروض حصرية.</p><form class="luxe-newsletter-form"><input type="email" placeholder="البريد الإلكتروني"><button class="luxe-btn luxe-btn--solid luxe-btn--md"><span class="luxe-btn__label">اشترك</span></button></form></div><div class="luxe-newsletter__img"><img src="{U(im[0],1000)}" alt=""></div></div></section>
</main>
<footer class="store-footer luxe-footer"><div class="container" style="padding-block:4rem 1rem;display:grid;gap:2rem;grid-template-columns:repeat(auto-fit,minmax(200px,1fr))"><div><h3 class="luxe-footer__brand">LUXE</h3><p>قطع مختارة بعناية.</p></div><div><h3>روابط</h3><p>من نحن<br>الشحن والتوصيل<br>سياسة الاسترجاع</p></div><div><h3>تواصل</h3><p>hello@luxe.sa</p></div></div><div class="luxe-wordmark">LUXE</div></footer></div>
<div class="lx-note">Static preview: real public/app.css + luxe.js (Salla widgets/icons absent)</div>
<script defer src="../public/luxe.js"></script></body></html>'''
out=pathlib.Path(__file__).resolve().parent.parent/"preview/index.html"; out.write_text(html); print("wrote",out)
